version: "3.7"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joshadow/laravel
    container_name: 365_food-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 6001:6001
    networks:
      - 365_food_api

  nginx:
    image: nginx:1.17-alpine
    container_name: 365_food-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - 365_food_api

networks:
  365_food_api:
    driver: bridge